### ISSUE TITLE
Weird new ResourceAccessException on UserTemplate.getRecentMedia

### ISSUE THREAD

**Issue by codeconsole** [mattupstate/spring-social-instagram#2]
```
org.springframework.web.client.ResourceAccessException: I/O error: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@ece0ca; line: 1, column: 2]; nested exception is org.codehaus.jackson.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.ByteArrayInputStream@ece0ca; line: 1, column: 2]
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:453)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:415)
    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:213)
    at org.springframework.social.instagram.api.impl.AbstractInstagramOperations.get(AbstractInstagramOperations.java:24)
    at org.springframework.social.instagram.api.impl.UserTemplate.getRecentMedia(UserTemplate.java:55)
```

**Comment by codeconsole** [comment]
Also getting these

```
org.springframework.web.client.ResourceAccessException: I/O error: Unexpected character ('O' (code 79)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@15043d3; line: 1, column: 2]; nested exception is org.codehaus.jackson.JsonParseException: Unexpected character ('O' (code 79)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
 at [Source: java.io.StringReader@15043d3; line: 1, column: 2]
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:453)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:415)
    at org.springframework.web.client.RestTemplate.getForObject(RestTemplate.java:213)
    at org.springframework.social.instagram.api.impl.AbstractInstagramOperations.get(AbstractInstagramOperations.java:24)
    at org.springframework.social.instagram.api.impl.UserTemplate.getRecentMedia(UserTemplate.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:43)
```
